# Supabase configuration for ADFD system

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://www.quandrox.com/dashboard"
additional_redirect_urls = [
  "https://www.quandrox.com/auth/callback",
  "https://www.quandrox.com/dashboard",
  "https://quandrox.com/auth/callback",
  "https://quandrox.com/dashboard",
  "http://localhost:5173/auth/callback",
  "http://localhost:5173/dashboard",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/dashboard"
]
jwt_expiry = 3600

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
shadow_port = 54320
major_version = 15
